# Generated by Django 4.0.4 on 2022-05-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess_the_number', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='game_time',
            field=models.IntegerField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='try_count',
            field=models.IntegerField(verbose_name='Кол-во попыток'),
        ),
        migrations.AlterModelTable(
            name='gameinfo',
            table='GameInfo',
        ),
    ]
