# Generated by Django 4.0.4 on 2022-05-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guess_the_number', '0002_alter_gameinfo_date_alter_gameinfo_game_time_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gameinfo',
            table='game_info',
        ),
    ]
